### ISSUE TITLE
Introduce CLA

### ISSUE THREAD

**Issue by Licenser** [spacejam/rio#16]
Hi,
this has been brought up in #3 to a degree but I'd like to suggest adding a CLA that assigns the copyright any of contributions to @spacejam - this would resolve any license ambiguities for contributions while still maintaining the ability to share the code under GPL and MIT for sponsors.

**Comment by Licenser** [comment]
since I'm doing research on this for other stuff, Linux's [DCO](https://developercertificate.org/) might be an option too

**Comment by spacejam** [comment]
I think this is a good idea due to the weird nature of the license structure. I just added one using https://github.com/cla-assistant/cla-assistant. Let's see how high-friction it is

**Comment by Licenser** [comment]
If you decide to keep it you might ask existing contributors to sign it after the fact, just to be sure you're covered

**Comment by Licenser** [comment]
I tested it in https://github.com/spacejam/rio/pull/19 - this is pretty painless, I'll lave the PR open so you can take a look at how it looks from your end, feel free to close it once you don't need it anymore.

**Comment by spacejam** [comment]
Thanks for testing :) I'll close this for now
