### ISSUE TITLE
too many files when opening many rings and reading

### ISSUE THREAD

**Issue by gauteh** [spacejam/rio#18]
Hi, this project looks very interesting. I've started trying it out, but I certainly do not understand io_uring completely yet. I tried to create some benchmarks in a project where I think io_uring would be useful. However, once I put it in the `Bencher::iter` loop I always get too many files open. Should I rather open one ring for the entire application? See test case which usually reproduces the error with `ulimit -n 1024`:

tests/many.rs:
```
use std::io::prelude::*;
use std::io::SeekFrom;

#[test]
fn test_loop() {
    let mut file = std::fs::OpenOptions::new()
        .create(true)
        .read(true)
        .write(true)
        .open("/tmp/rio-test-loop-data")
        .unwrap();

    file.write(b"hello hello again").unwrap();
    file.seek(SeekFrom::Start(0)).unwrap(); // unnecessary? 

    for _ in 0..1024 {
        let ring = rio::new().unwrap();
        let mut buf = vec![0_u8; 17];
        ring.read_at(&file, &mut buf, 0).wait().unwrap();
        assert_eq!(buf, b"hello hello again");
    }

    std::fs::remove_file("/tmp/rio-test-loop-data").unwrap(); // does not (usually) get called
}
```

**Comment by gauteh** [comment]
Branch with test is here: https://github.com/gauteh/rio/tree/test_many_files

**Comment by spacejam** [comment]
yeah, io_uring requires allocating some locked memory, which is usually a pretty finite resource on most systems, so spinning up a uring per iteration is going to hit that. feel free to just use one for the whole application's lifetime.

**Comment by gauteh** [comment]
Thanks for your answer. That explains why I kept running into that issue as well. Should not the ring close the fd's when it is dropped at the end of each iteration?
