### ISSUE TITLE
Mention that this crate is unsound in the README

### ISSUE THREAD

**Issue by bill-myers** [spacejam/rio#25]
It appears that this crate has multiple soundness issues as evidenced by several issues, yet the fact that it is currently broken is not mentioned in the README, creating a false impression.

**Comment by spacejam** [comment]
not broken. rust broken. single intentional unsoundness possibility that is documented in the Completion docs.

**Comment by nox** [comment]
How is it Rust that is broken if no one needs to `mem::forget` nor `ManuallyDrop` to trigger a leak and undefined behaviour, and `libstd` itself chose to remove something similar (the scoped threading APIs) because of the unsoundness?

**Comment by jasoncarr0** [comment]
No matter the feelings on Rust here, I think it is worthwhile to mention that this does not follow the safety guarantees that Rust expects for safe code. You can certainly segue into why you disagree

**Comment by Lucretiel** [comment]
>  single intentional unsoundness possibility that is documented in the Completion docs.

Why not mark the relevant API surface as `unsafe`? The entire promise of the Rust ecosystem is that it's not possible to cause unsoundness with only safe code.
