### ISSUE TITLE
Consider licensing issues

### ISSUE THREAD

**Issue by mpdn** [spacejam/rio#3]
Cool library, but I would be wary of the way the license is structured. From the description:

>GPL-3.0 nice bindings for io_uring. MIT/Apache-2.0 license is available for spacejam's github sponsors.

You cannot re-license other peoples' work, so this precludes accepting any pull requests made under the GPL.

**Comment by spacejam** [comment]
The MIT/Apache-2.0 version does not include the 7 lines of code that were contributed by someone else, which are not necessary for any of the crate's functionality, but more for certain perf tuning situations.

**Comment by mpdn** [comment]
Oh sure, this was more of a heads up wrt. any potential future PRs.

**Comment by spacejam** [comment]
Thanks for opening the issue! The nice thing about this library is that it has a pretty small API surface to map, and it's probably unlikely to need a lot more work before I can maintenance-mode it and just start using it in lots of things.

**Comment by Licenser** [comment]
I would have a few questions on the topic I hope putting them in here is OK.

First of all, please don't read this as a 'but I want work for free!!!' post, I've done open source work long enough that I think hate how companies do not pay for work that deserves to be paid for. What I'm unclear about is the consequences of the dual license in the long run or for projects using it.

If someone decide to use rio in a project and become a sponsor would anyone in using that project also have to become a sponsor or it'd have to count as GPL for them?

What would happen if someone sponsoring creates a project around rio and at some point in the future stops, would the project then fall back into GPL or remain under whatever license the project picked?

Back to the original question brought up by @mpdn. How does that apply to projects using rio with multiple authors or that accept pull requests from third parties, would everyone contributing to the project have to sponsor rio?

**Comment by spacejam** [comment]
Apache-2.0 states that the license is irrevocable and the subjected work is free to transfer (at the license holder's terms, as long as the Apache-2.0 license is distributed along with it), so any use from that point onward is Apache-2.0. MIT can also be distributed and sublicensed as long as the license remains intact. So, anyone who gets these licenses can give it to anyone else, including by just publishing a crate with a different name that has the same code, but that forces them to act in sort of an obviously asshole way, incurring bad karma.

My aim with this is to make it clear that I want people to help me if I'm writing things that help them, so I can keep building helpful things. I don't have a job right now and this is an ongoing experiment in sustainability.

**Comment by Licenser** [comment]
Thank you for the clarification! That makes perfect sense.
