### ISSUE TITLE
Can only create two instances

### ISSUE THREAD

**Issue by cshuaimin** [spacejam/rio#4]
Hi, I get "Cannot allocate memory" error when creating the third instance, even if the first two are dropped. Code
```rust
fn main() {
    for _ in 0..4 {
        println!("{:?}", rio::new().map(|_| ()));
    }
}
```
outputs
```
Ok(())
Ok(())
Err(Os { code: 12, kind: Other, message: "Cannot allocate memory" })
Err(Os { code: 12, kind: Other, message: "Cannot allocate memory" })
```
I am using rio 0.7.5 on Linux 5.4.13 and I'm sure there's enough memory.

**Comment by spacejam** [comment]
You are hitting the per-user rlimit for memlock. See https://github.com/spacejam/sled/issues/899

As this library is meant to be misuse-resistant, I should improve that error message to refer to this.

**Comment by spacejam** [comment]
@cshuaimin I just cut rio `0.7.6` which will add additional info if error 12 is hit during initialization, specifying that you need to raise the memlock rlimit. This interface relies on preventing the memory shared between userspace and the kernel from ever being paged-out, but it can quickly eat through the system's per-process limit for such memory, which is often set quite low. Please feel free to re-open this issue if adjusting your rlimit does not address the issue.

**Comment by cshuaimin** [comment]
Increasing the memlock limit solves this issue. Thank you for your patience!

BTW, talking to misuse-resistance, passing a `Vec<u8>` directly (not by a reference) to `write_at` will write garbage to the file without any compiling error:

```rust
fn main() {
    let file = std::fs::File::create("data").unwrap();
    let rio = rio::new().unwrap();
    let buffer: Vec<u8> = b"hello world!".to_vec();
    rio.write_at(&file, buffer, 0).unwrap().wait().unwrap();  // <- this succeed, but the file content is random
}

```

**Comment by spacejam** [comment]
@cshuaimin thank you very much for mentioning that! I just cut rio `0.8.0` which changes the API to guarantee no buffer is ever passed-in by value, and ensuring that all buffers live at least as long as the Completion remains outstanding.

**Comment by cshuaimin** [comment]
Cool!
